// <auto-generated />
using System;
using CbTsSa_Shared.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CbTsSa_Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CbTsSa_Shared.DBModels.AdditionalDiscount", b =>
                {
                    b.Property<long>("GatheredBasketID")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorisedByUserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GatheredBasketID");

                    b.HasIndex("AuthorisedByUserID");

                    b.ToTable("AdditionalDiscounts");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CurrentOrderJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DtTmJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool?>("POPIConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SocialMedia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserIndicatedCell")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CellNumber")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.BroadcastCampaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampaignId"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveredCount")
                        .HasColumnType("integer");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("InitiatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("ReadCount")
                        .HasColumnType("integer");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRecipients")
                        .HasColumnType("integer");

                    b.HasKey("CampaignId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("InitiatedByUserId", "CreatedDateTime");

                    b.HasIndex("BusinessId", "Status", "CreatedDateTime");

                    b.ToTable("BroadcastCampaigns", t =>
                        {
                            t.HasCheckConstraint("CK_BroadcastCampaign_RecipientCounts", "\"TotalRecipients\" >= 0 AND \"SentCount\" >= 0 AND \"DeliveredCount\" >= 0 AND \"ReadCount\" >= 0 AND \"FailedCount\" >= 0");
                        });
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.BroadcastMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReadDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("SentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WhatsAppMessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MessageId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("WhatsAppMessageId");

                    b.HasIndex("CampaignId", "Status");

                    b.HasIndex("Status", "CreatedDateTime")
                        .HasFilter("\"Status\" = 'Queued'");

                    b.ToTable("BroadcastMessages");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.BroadcastTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime?>("ApprovedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<string>("ButtonsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CampaignImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FooterText")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("HeaderText")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("HeaderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WhatsAppTemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TemplateId");

                    b.HasIndex("CampaignImageId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WhatsAppTemplateId");

                    b.HasIndex("BusinessId", "CreatedByUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_BroadcastTemplate_OnePerUser");

                    b.HasIndex("BusinessId", "Name")
                        .IsUnique();

                    b.HasIndex("BusinessId", "Status", "CreatedDateTime");

                    b.ToTable("BroadcastTemplates");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Bundle", b =>
                {
                    b.Property<long>("BundleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BundleID"));

                    b.Property<long>("ItemID")
                        .HasColumnType("bigint");

                    b.HasKey("BundleID");

                    b.HasIndex("BundleID")
                        .IsUnique();

                    b.HasIndex("ItemID");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Business", b =>
                {
                    b.Property<long>("BusinessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BusinessID"));

                    b.Property<long?>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<byte?>("AccountType")
                        .HasColumnType("smallint");

                    b.Property<byte?>("AverageRating")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bank")
                        .HasColumnType("smallint");

                    b.Property<int?>("BranchNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<long>("Cellnumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("GPSLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("GPSLong")
                        .HasColumnType("decimal(9,6)");

                    b.Property<byte>("Industry")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("LocationLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewUserGreeting_Cold")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("NewUserGreeting_Warm")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("PostalAddress")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<bool?>("PostalSameAsStreet")
                        .HasColumnType("boolean");

                    b.Property<string>("PricelistPreamble")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("RegisteredName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("TradingHours")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TradingName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Twitter")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("VATNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Website")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("BusinessID");

                    b.HasIndex("Cellnumber")
                        .IsUnique();

                    b.HasIndex("RegisteredName")
                        .IsUnique();

                    b.HasIndex("Industry", "TradingName")
                        .IsUnique();

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.CampaignImage", b =>
                {
                    b.Property<int>("CampaignImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampaignImageId"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessMediaHandle")
                        .HasMaxLength(255)
                        .HasColumnType("text");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalStorageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MediaHandle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("UploadedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CampaignImageId");

                    b.HasIndex("BusinessMediaHandle")
                        .HasFilter("\"BusinessMediaHandle\" IS NOT NULL");

                    b.HasIndex("MediaHandle");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("BusinessId", "UploadedDateTime");

                    b.HasIndex("BusinessId", "UploadedByUserId", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_CampaignImage_OnePerUser")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex(new[] { "BusinessId", "MediaHandle" }, "IX_CampaignImage_Business_MediaHandle")
                        .IsUnique();

                    b.HasIndex(new[] { "BusinessId", "UploadedByUserId", "IsActive" }, "IX_CampaignImage_Business_User_Active");

                    b.ToTable("CampaignImages");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Catalog", b =>
                {
                    b.Property<long>("CatalogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CatalogID"));

                    b.Property<long>("BusinessID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorUserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.HasKey("CatalogID");

                    b.HasIndex("BusinessID");

                    b.HasIndex("CreatorUserID");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.CatalogItem", b =>
                {
                    b.Property<long>("CatalogID")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("ItemID")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CatalogID", "ItemID");

                    b.HasIndex("ItemID");

                    b.HasIndex("CatalogID", "MenuCode")
                        .IsUnique()
                        .HasDatabaseName("IX_CatalogItem_Catalog_MenuCode");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Comment", b =>
                {
                    b.Property<long>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CommentID"));

                    b.Property<string>("CommentText")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<byte?>("Rating")
                        .HasColumnType("smallint");

                    b.Property<long?>("ResponseToCommentID")
                        .HasColumnType("bigint");

                    b.Property<long>("SaleableID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("CommentID");

                    b.HasIndex("ResponseToCommentID");

                    b.HasIndex("SaleableID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Delivery", b =>
                {
                    b.Property<long>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliveryID"));

                    b.Property<string>("DriverAcceptedLocation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DtTmClosed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DtTmCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DtTmDriverAccepted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DtTmDriverOnScene")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeliveryID");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.DeliveryDriverLeg", b =>
                {
                    b.Property<long>("DeliveryDriverLegID")
                        .HasColumnType("bigint");

                    b.Property<long>("DeliveryLegID")
                        .HasColumnType("bigint");

                    b.Property<long>("SaleID")
                        .HasColumnType("bigint");

                    b.Property<string>("DriverID")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<long>("DeliveryID")
                        .HasColumnType("bigint");

                    b.HasKey("DeliveryDriverLegID", "DeliveryLegID", "SaleID", "DriverID");

                    b.HasIndex("DeliveryID");

                    b.HasIndex("DriverID");

                    b.HasIndex("DeliveryLegID", "SaleID");

                    b.ToTable("DeliveryDriverLegs");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.DeliveryLeg", b =>
                {
                    b.Property<long>("DeliveryLegID")
                        .HasColumnType("bigint");

                    b.Property<long>("SaleID")
                        .HasColumnType("bigint");

                    b.Property<string>("DisputedReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("DtTmArrivedAtCust")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DtTmCollected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DtTmDisputed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DtTmDriverOnScene")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DtTmOTPPassed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DtTmPaid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DtTmResolved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resolution")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("DeliveryLegID", "SaleID");

                    b.HasIndex("SaleID");

                    b.ToTable("DeliveryLegs");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Driver", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<double?>("GPSLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("GPSLong")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LocationLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserID");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.EffectiveBasket", b =>
                {
                    b.Property<long>("EffectiveBasketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EffectiveBasketID"));

                    b.Property<string>("AuthorisedByUserID")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<decimal?>("EffectiveDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("GatheredBasketID")
                        .HasColumnType("bigint");

                    b.HasKey("EffectiveBasketID");

                    b.HasIndex("AuthorisedByUserID");

                    b.HasIndex("GatheredBasketID")
                        .IsUnique();

                    b.ToTable("EffectiveBaskets");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Failed", b =>
                {
                    b.Property<long>("FailedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FailedID"));

                    b.Property<DateTime>("FailureDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("boolean");

                    b.Property<int>("MopaErrorCode")
                        .HasColumnType("integer");

                    b.Property<string>("PayGateBankAuthID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("PayGateResultCode")
                        .HasColumnType("integer");

                    b.Property<byte?>("PayGateTransactionCode")
                        .HasColumnType("smallint");

                    b.Property<int?>("PayGateTransactionID")
                        .HasColumnType("integer");

                    b.Property<int?>("PayGateValidationErrorCode")
                        .HasColumnType("integer");

                    b.Property<long?>("PaymentID")
                        .HasColumnType("bigint");

                    b.HasKey("FailedID");

                    b.HasIndex("PaymentID");

                    b.ToTable("FailedPayments");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.FoodPoisoningReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("DateTimeReported")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FoodItem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IncidentAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PeopleAffected")
                        .HasColumnType("integer");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodPoisoningReports");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.GatheredBasket", b =>
                {
                    b.Property<long>("GatheredBasketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GatheredBasketID"));

                    b.Property<long>("BundleID")
                        .HasColumnType("bigint");

                    b.Property<int>("BundleMultiplier")
                        .HasColumnType("integer");

                    b.HasKey("GatheredBasketID");

                    b.HasIndex("BundleID")
                        .IsUnique();

                    b.ToTable("GatheredBaskets");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Good", b =>
                {
                    b.Property<long>("GoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GoodID"));

                    b.Property<long?>("Barcode")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<long?>("ManufacturerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("GoodID");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Item", b =>
                {
                    b.Property<long>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemID"));

                    b.Property<long>("PurchasableID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SpecialID")
                        .HasColumnType("bigint");

                    b.HasKey("ItemID");

                    b.HasIndex("PurchasableID");

                    b.HasIndex("SpecialID");

                    b.HasIndex("ItemID", "PurchasableID", "SpecialID")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Offer", b =>
                {
                    b.Property<long>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OfferID"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedByUserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("OfferDtTmEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OfferDtTmStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("OfferTypeID")
                        .HasColumnType("smallint");

                    b.HasKey("OfferID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("OfferTypeID");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.OfferType", b =>
                {
                    b.Property<byte>("OfferTypeID")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("OfferTypeID");

                    b.ToTable("OfferTypes");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Payment", b =>
                {
                    b.Property<long>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentID"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("CardID")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("InitiationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayGateBankAuthID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("PayGateTransactionID")
                        .HasColumnType("integer");

                    b.Property<long?>("SaleID")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte?>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SuccesfulDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentID");

                    b.HasIndex("SaleID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductID"));

                    b.Property<long>("BusinessID")
                        .HasColumnType("bigint");

                    b.Property<long>("GoodID")
                        .HasColumnType("bigint");

                    b.HasKey("ProductID");

                    b.HasIndex("BusinessID");

                    b.HasIndex("GoodID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.HasIndex("ProductID", "BusinessID")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Purchasable", b =>
                {
                    b.Property<long>("PurchasableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PurchasableID"));

                    b.Property<long>("OfferID")
                        .HasColumnType("bigint");

                    b.Property<long>("SaleableID")
                        .HasColumnType("bigint");

                    b.HasKey("PurchasableID");

                    b.HasIndex("OfferID");

                    b.HasIndex("SaleableID");

                    b.HasIndex("PurchasableID", "SaleableID", "OfferID")
                        .IsUnique();

                    b.ToTable("Purchasables");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Refund", b =>
                {
                    b.Property<long>("RefundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RefundID"));

                    b.Property<DateTime>("InitiationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayGateBankAuthID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("PayGateTransactionID")
                        .HasColumnType("integer");

                    b.Property<long?>("PaymentID")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SuccesfulDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RefundID");

                    b.HasIndex("PaymentID");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Sale", b =>
                {
                    b.Property<long>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SaleID"));

                    b.Property<bool>("DontPoolWithStrangers")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DtTmCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DtTmRequestedCheckout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAmtManual")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("SaleID");

                    b.HasIndex("UserID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.SaleBasket", b =>
                {
                    b.Property<long>("SaleID")
                        .HasColumnType("bigint");

                    b.Property<long>("EffectiveBasketID")
                        .HasColumnType("bigint");

                    b.HasKey("SaleID", "EffectiveBasketID");

                    b.HasIndex("EffectiveBasketID")
                        .IsUnique();

                    b.ToTable("SaleBaskets");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.SaleStatus", b =>
                {
                    b.Property<long>("SaleID")
                        .HasColumnType("bigint");

                    b.Property<long>("ChangedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DtTmStatusChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("NewStatusID")
                        .HasColumnType("smallint");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SaleID", "ChangedByUserID", "DtTmStatusChanged", "NewStatusID");

                    b.HasIndex("NewStatusID");

                    b.ToTable("SaleStatuses");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Saleable", b =>
                {
                    b.Property<long>("SaleableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SaleableID"));

                    b.Property<bool>("IsService")
                        .HasColumnType("boolean");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ServiceID")
                        .HasColumnType("bigint");

                    b.HasKey("SaleableID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.HasIndex("ServiceID")
                        .IsUnique();

                    b.ToTable("Saleables");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Service", b =>
                {
                    b.Property<long>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ServiceID"));

                    b.Property<long>("BusinessID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServiceID");

                    b.HasIndex("BusinessID", "Name")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.SignedUpWith", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeSignedUp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("UserId", "BusinessId")
                        .IsUnique()
                        .HasDatabaseName("IX_SignedUpWith_UserBusiness");

                    b.ToTable("SignedUpWith");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Special", b =>
                {
                    b.Property<long>("SpecialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SpecialID"));

                    b.Property<string>("CreatedByUserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("SpecialDescription")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("SpecialDtTmEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SpecialDtTmStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("SpecialID");

                    b.HasIndex("CreatedByUserID");

                    b.ToTable("Specials");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Status", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.UserIdImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MediaHandle")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ProcessedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text");

                    b.Property<string>("StorageType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UploadedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "ImageType")
                        .IsUnique()
                        .HasDatabaseName("IX_UserIdImage_UserType");

                    b.ToTable("UserIdImages");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.UserSignUp", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateTimeSubmitted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstSignedUpWith")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("UserId");

                    b.ToTable("UserSignUps");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUserToken");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.ApplicationUserToken", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserToken<string>");

                    b.Property<DateTime?>("DttmIssued")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("1");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.AdditionalDiscount", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "AuthorisedByUser")
                        .WithMany()
                        .HasForeignKey("AuthorisedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.GatheredBasket", "GatheredBasket")
                        .WithMany("AdditionalDiscounts")
                        .HasForeignKey("GatheredBasketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorisedByUser");

                    b.Navigation("GatheredBasket");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.BroadcastCampaign", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.BroadcastTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("InitiatedByUser");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.BroadcastMessage", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.BroadcastCampaign", "Campaign")
                        .WithMany("Messages")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.BroadcastTemplate", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.CampaignImage", "CampaignImage")
                        .WithMany()
                        .HasForeignKey("CampaignImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("CampaignImage");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Bundle", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.CampaignImage", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Catalog", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Business", "Business")
                        .WithMany("Catalogs")
                        .HasForeignKey("BusinessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.CatalogItem", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Catalog", "Catalog")
                        .WithMany("CatalogItems")
                        .HasForeignKey("CatalogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.Item", "Item")
                        .WithMany("CatalogItems")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Comment", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Comment", "ResponseToComment")
                        .WithMany()
                        .HasForeignKey("ResponseToCommentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbTsSa_Shared.DBModels.Saleable", "Saleable")
                        .WithMany("Comments")
                        .HasForeignKey("SaleableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResponseToComment");

                    b.Navigation("Saleable");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.DeliveryDriverLeg", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Delivery", "Delivery")
                        .WithMany("DeliveryDriverLegs")
                        .HasForeignKey("DeliveryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.DeliveryLeg", "DeliveryLeg")
                        .WithMany("DeliveryDriverLegs")
                        .HasForeignKey("DeliveryLegID", "SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("DeliveryLeg");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.DeliveryLeg", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Sale", "Sale")
                        .WithMany("DeliveryLegs")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Driver", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.EffectiveBasket", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "AuthorisedByUser")
                        .WithMany()
                        .HasForeignKey("AuthorisedByUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CbTsSa_Shared.DBModels.GatheredBasket", "GatheredBasket")
                        .WithOne()
                        .HasForeignKey("CbTsSa_Shared.DBModels.EffectiveBasket", "GatheredBasketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorisedByUser");

                    b.Navigation("GatheredBasket");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Failed", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Payment", "Payment")
                        .WithMany("Failures")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.FoodPoisoningReport", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.GatheredBasket", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Bundle", "Bundle")
                        .WithMany()
                        .HasForeignKey("BundleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Item", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Purchasable", "Purchasable")
                        .WithMany()
                        .HasForeignKey("PurchasableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.Special", "Special")
                        .WithMany()
                        .HasForeignKey("SpecialID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Purchasable");

                    b.Navigation("Special");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Offer", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.OfferType", "OfferType")
                        .WithMany()
                        .HasForeignKey("OfferTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("OfferType");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Payment", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Product", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Business", "Business")
                        .WithMany("Products")
                        .HasForeignKey("BusinessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.Good", "Good")
                        .WithMany()
                        .HasForeignKey("GoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Good");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Purchasable", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.Saleable", "Saleable")
                        .WithMany()
                        .HasForeignKey("SaleableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Saleable");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Refund", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Sale", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.SaleBasket", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.EffectiveBasket", "EffectiveBasket")
                        .WithOne()
                        .HasForeignKey("CbTsSa_Shared.DBModels.SaleBasket", "EffectiveBasketID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.Sale", "Sale")
                        .WithMany("SaleBaskets")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EffectiveBasket");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.SaleStatus", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Status", "Status")
                        .WithMany("SaleStatuses")
                        .HasForeignKey("NewStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.Sale", "Sale")
                        .WithMany("SaleStatuses")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Saleable", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Product", "Product")
                        .WithOne()
                        .HasForeignKey("CbTsSa_Shared.DBModels.Saleable", "ProductID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CbTsSa_Shared.DBModels.Service", "Service")
                        .WithOne()
                        .HasForeignKey("CbTsSa_Shared.DBModels.Saleable", "ServiceID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Service", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Business", "Business")
                        .WithMany("Services")
                        .HasForeignKey("BusinessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.SignedUpWith", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.Business", "Business")
                        .WithMany("UsersSignedUp")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "User")
                        .WithMany("SignedUpWithBusinesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Special", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.UserIdImage", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.UserSignUp", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CbTsSa_Shared.DBModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.ApplicationUser", b =>
                {
                    b.Navigation("SignedUpWithBusinesses");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.BroadcastCampaign", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Business", b =>
                {
                    b.Navigation("Catalogs");

                    b.Navigation("Products");

                    b.Navigation("Services");

                    b.Navigation("UsersSignedUp");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Catalog", b =>
                {
                    b.Navigation("CatalogItems");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Delivery", b =>
                {
                    b.Navigation("DeliveryDriverLegs");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.DeliveryLeg", b =>
                {
                    b.Navigation("DeliveryDriverLegs");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.GatheredBasket", b =>
                {
                    b.Navigation("AdditionalDiscounts");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Item", b =>
                {
                    b.Navigation("CatalogItems");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Payment", b =>
                {
                    b.Navigation("Failures");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Sale", b =>
                {
                    b.Navigation("DeliveryLegs");

                    b.Navigation("Payments");

                    b.Navigation("SaleBaskets");

                    b.Navigation("SaleStatuses");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Saleable", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("CbTsSa_Shared.DBModels.Status", b =>
                {
                    b.Navigation("SaleStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
